### PR TITLE
fixed handle_input call

### PR DESCRIPTION
**Pull request by mdxe**
try this (untested as I don't have an RPi or LoRa hardware)...

### CODE REVIEW

**Comment by dmahony** [comment]
Well done! I could probably get you a pair of cheap Lora Modules if you could get the Raspberry Pi!

**Comment by mdxe** [comment]
thanks.  That'd be nice if you could spare a couple LoRa modules.  It looks like they are out of stock of the Pi Zero around here but I will order them as soon as possible

**Comment by dmahony** [comment]
@mdxe I don't have any spares but It should be cheap for 2 RFM98 modules, I'm happy to get you a pair for testing (eventually, Xmas is expensive!) but for the mean time I can give you remote access to my two Raspberry Pi's and a RTL-SDR (if you want to use it for monitoring the signal)
What do you think? Would you want to try remote access?

**Comment by mdxe** [comment]
@dmahony I won't have much time to play with this until after new year but remote access should work fine.

**Pull request merged**
